### ISSUE TITLE
AttributeError when inheriting to the same child from the same parent directory

### ISSUE THREAD

**Issue by jkrysl** [psss/fmf#27]
I hit an easy to reproduce traceback when defining same leaf with different methods (using 2 files from same location). If I define it using `main.fmf` and `1/main.fmf`, there is no issue. But doing the same thing using `main.fmf` and `1.fmf` leads to following traceback: 
```
# tree
.
├── 1.fmf
└── main.fmf

# cat 1.fmf
in_1: True

# cat main.fmf
/1:
  in_main: True

# fmf
Traceback (most recent call last):
  File "/usr/bin/fmf", line 4, in <module>
    __import__('pkg_resources').run_script('fmf==0.4.1', 'fmf')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/fmf-0.4.1-py2.7.egg/EGG-INFO/scripts/fmf", line 35, in <module>

  File "build/bdist.linux-x86_64/egg/fmf/cli.py", line 120, in main
  File "build/bdist.linux-x86_64/egg/fmf/base.py", line 57, in __init__
  File "build/bdist.linux-x86_64/egg/fmf/base.py", line 152, in grow
  File "build/bdist.linux-x86_64/egg/fmf/base.py", line 107, in child
  File "build/bdist.linux-x86_64/egg/fmf/base.py", line 124, in grow
AttributeError: 'dict' object has no attribute 'rstrip'
```
This is reproducible since the very beginning, so no regression:
```
# fmf
Traceback (most recent call last):
  File "/usr/bin/fmf", line 4, in <module>
    __import__('pkg_resources').run_script('fmf==0.1.1', 'fmf')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/fmf-0.1.1-py2.7.egg/EGG-INFO/scripts/fmf", line 35, in <module>

  File "build/bdist.linux-x86_64/egg/fmf/cli.py", line 96, in main
  File "build/bdist.linux-x86_64/egg/fmf/base.py", line 50, in __init__
  File "build/bdist.linux-x86_64/egg/fmf/base.py", line 115, in grow
  File "build/bdist.linux-x86_64/egg/fmf/base.py", line 82, in child
  File "build/bdist.linux-x86_64/egg/fmf/base.py", line 90, in grow
AttributeError: 'dict' object has no attribute 'rstrip'
```

**Comment by psss** [comment]
This should be also fixed by 6d3da7f.
