### ISSUE TITLE
Running 'fmf init' with '.fmf' file present leads to 'OSError: [Errno 17] File exists'

### ISSUE THREAD

**Issue by jkrysl** [psss/fmf#37]
$ fmf init
Traceback (most recent call last):
  File "/usr/bin/fmf", line 4, in <module>
    __import__('pkg_resources').run_script('fmf==0.5.1', 'fmf')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/fmf-0.5.1-py2.7.egg/EGG-INFO/scripts/fmf", line 35, in <module>
    
  File "build/bdist.linux-x86_64/egg/fmf/cli.py", line 194, in main
  File "build/bdist.linux-x86_64/egg/fmf/cli.py", line 73, in __init__
  File "build/bdist.linux-x86_64/egg/fmf/cli.py", line 145, in command_init
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/home/jkrysl/tests/python-stqe/tests/.fmf'

**Comment by psss** [comment]
For existing directory a reasonable error message is displayed:

    > mkdir .fmf
    > fmf init
    [ ERROR ] Directory '/tmp/dir/.fmf' already exists.

This seems to be caused by a file of the same name. But we should handle this as well.
