### ISSUE TITLE
Docs: example fails

### ISSUE THREAD

**Issue by Andrei-Stepanov** [psss/fmf#38]
Hi,

I am not sure if this is a wrong example, but it fails:

http://fmf.readthedocs.io/en/latest/examples.html

```
fmf      
Traceback (most recent call last):
  File "/usr/bin/fmf", line 35, in <module>
    fmf.cli.main()
  File "/usr/lib/python2.7/site-packages/fmf/cli.py", line 120, in main
    tree = fmf.Tree(path)
  File "/usr/lib/python2.7/site-packages/fmf/base.py", line 57, in __init__
    self.grow(data)
  File "/usr/lib/python2.7/site-packages/fmf/base.py", line 146, in grow
    data = yaml.load(datafile)
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib64/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib64/python2.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib64/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib64/python2.7/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/lib64/python2.7/site-packages/yaml/scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "/usr/lib64/python2.7/site-packages/yaml/scanner.py", line 149, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/usr/lib64/python2.7/site-packages/yaml/scanner.py", line 289, in stale_possible_simple_keys
    "could not found expected ':'", self.get_mark())
yaml.scanner.ScannerError: while scanning a simple key
  in "/home/astepano/shared/osci/standard-test-roles/3.fmf", line 6, column 1
could not found expected ':'
  in "/home/astepano/shared/osci/standard-test-roles/3.fmf", line 7, column 16





➜  standard-test-roles git:(master_copr_build) ✗ cat 3.fmf 
description: Check basic download options
tags: [Tier2, TierSecurity]
test: runtest.sh
time: 3 min

/requirements
    requirement: Various download options working correctly
    priority: low
    /get-file:
        coverage: wget/download
    /output-document:
        coverage: wget/download
    /continue:
    /timestamping:
    /tries:
    /no-clobber:
        coverage: wget/download
    /progress:
    /quota:
    /server-response:
    /bind-address:
    /spider:

```

**Comment by Andrei-Stepanov** [comment]
fmf-0.4-1.el7.noarch

**Comment by AloisMahdal** [comment]
I don't understand the traceback but maybe it could be related to the recent change in dir format?

Could you please try it with *fmf-0.5* (it's in COPR) and make sure the directory is initialized (ie. has `.fmf/version`)?

**Comment by jkrysl** [comment]
It seems there is an error in the example:
`/requirements` should be `/requirements:`

I am able to reproduce this by just missing out the `:` at the end of leaf specification.

The trace says it clearly `"could not found expected ':'", self.get_mark())` though I agree it should not say it with trace but catch the error :)
