### ISSUE TITLE
tmt (in fmf module) dies in pain (traceback) when CWD is not accessible

### ISSUE THREAD

**Issue by marmolak** [psss/fmf#66]
Hello.
tmt raises traceback when CWD lost rights to read/execute.

How to reproduce:

under root user:
# cd ~
# ls -lad /root/
dr-xr-x---. 4 root root 226 Nov 14 03:26 /root/
[root@koza-6 ~]#  su rhack
[rhack@koza-6 root]$ tmt
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/fmf/base.py", line 96, in _initialize
    while ".fmf" not in next(os.walk(root))[1]:
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/tmt", line 11, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 763, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 716, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1113, in invoke
    return Command.invoke(self, ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 955, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 554, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/tmt/cli.py", line 159, in main
    tmt.Test.overview(tree)
  File "/usr/lib/python3.7/site-packages/tmt/base.py", line 122, in overview
    style(str(test), fg='red') for test in tree.tests()]
  File "/usr/lib/python3.7/site-packages/tmt/base.py", line 489, in tests
    return [Test(test) for test in self.tree.prune(
  File "/usr/lib/python3.7/site-packages/tmt/base.py", line 466, in tree
    self._tree = fmf.Tree(self._path)
  File "/usr/lib/python3.7/site-packages/fmf/base.py", line 74, in __init__
    self._initialize(path=data)
  File "/usr/lib/python3.7/site-packages/fmf/base.py", line 103, in _initialize
    raise utils.FileError("Invalid directory path: {0}".format(root))
fmf.utils.FileError: Invalid directory path: /root

Something better than traceback would be nice :). Yeah, It's corner case but.. I happened! :)

**Comment by psss** [comment]
The error output should now be much more sane:

```shell
> mkdir /tmp/access
> cd /tmp/access
> chmod ugo-rwx .
> tmt
Invalid yaml syntax: Invalid directory path: /tmp/access
```
